version: '2'
services:
  reactapp-app:
    image: reactapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://reactapp-mssql:1433;database=reactapp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://reactapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://reactapp-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8690:8690
  reactapp-mssql:
    extends:
      file: mssql.yml
      service: reactapp-mssql
  reactapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: reactapp-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
